name: Push To Update API
description: "Action for pushing a release to the update API"
inputs:
  version:
    required: true
  platform:
    required: true
  file-name:
    required: true
  file-hash:
    required: true
  file-size:
    required: true
  update-service-token:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: >
        curl -X 'POST'
        'https://update.api.macro-deck.app/files/${{ inputs.version }}/${{ inputs.platform }}'
        -H 'accept: */*'
        -H 'x-admin-token: ${{ inputs.update-service-token }}'
        -H 'Content-Type: application/json'
        -d '{
        "fileName": ${{ inputs.file-name }},
        "fileProvider": "GitHub",
        "fileHash": ${{ inputs.file-hash }},
        "fileSize": ${{ inputs.file-size }}
        }'