name: Discord Notify Release
description: "Action for notifying a new release on the Discord server using Macro-Bot"
inputs:
  webhook_key:
    required: true
  isBeta:
    required: true
  version:
    required: true

runs:
  using: "composite"
  steps:
    - name: "Notify Release"
      if: ${{ inputs.isBeta == 'false' }}
      continue-on-error: true
      shell: bash
      run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ inputs.webhook_key }}" \
            -d '{
              "toEveryone": false,
              "embed": {
                "color": {
                  "r": 0,
                  "g": 1,
                  "b": 0
                },
                "description": "**${{ inputs.version }} is now released!**",
                "fields": [
                  {
                    "name": "Channel",
                    "value": "Release",
                    "inline": false
                  },
                  {
                    "name": "Changelog",
                    "value": "https://github.com/Macro-Deck-App/Macro-Deck/releases/tag/v${{ inputs.version }}",
                    "inline": false
                  }
                ]
              }
            }' \
            https://bot.api.macro-deck.app/webhook/macro-deck-release

    - name: "Notify Beta Release"
      if: ${{ inputs.isBeta == 'true' }}
      continue-on-error: true
      shell: bash
      run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ inputs.webhook_key }}" \
            -d '{
              "toEveryone": false,
              "embed": {
                "color": {
                  "r": 0,
                  "g": 1,
                  "b": 0
                },
                "description": "**Beta ${{ inputs.version }} is now released!**",
                "fields": [
                  {
                    "name": "Channel",
                    "value": "Beta",
                    "inline": false
                  },
                  {
                    "name": "Changelog",
                    "value": "https://github.com/Macro-Deck-App/Macro-Deck/releases/tag/v${{ inputs.version }}",
                    "inline": false
                  }
                ]
              }
            }' \
            https://bot.api.macro-deck.app/webhook/macro-deck-beta-release