name: Get Upload URL
description: "Action for getting the upload url for a GitHub release"
inputs:
  version:
    required: true
  github-token:
    required: true
outputs:
  upload-url:
    value: ${{ steps.create_release.outputs.result }}
    description: "The URL for uploading assets to the release"

runs:
  using: "composite"
  steps:
    - uses: "actions/github-script@v6.4.1"
      id: create_release
      with:
        github-token: "${{ inputs.github-token }}"
        script: |
            const response = await github.request('GET /repos/${{github.repository}}/releases/tags/v${{inputs.version}}');
            return response.data.upload_url;