name: Deploy
description: "Action for deploying a service"
inputs:
  host:
    type: string
    required: true
  user:
    type: string
    required: true
  key:
    type: string
    required: true
  service:
    type: string
    required: true
  sha:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/server.key
        chmod 600 ~/.ssh/server.key
        cat >>~/.ssh/config <<END
        Host server
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/server.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ inputs.user }}
        SSH_KEY: ${{ inputs.key }}
        SSH_HOST: ${{ inputs.host }}

    - name: Execute deploy script
      shell: bash
      run: ssh server './deploy-service.sh ${{ inputs.service }} ${{ inputs.sha }}'