name: Deploy
description: "Action for deploying a service"
inputs:
  host:
    type: string
    required: true
  user:
    type: string
    required: true
  key:
    type: string
    required: true
  service:
    type: string
    required: true
  sha:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        rm -f ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/server.key
        chmod 600 ~/.ssh/server.key
        ssh-keyscan -t rsa -H $SSH_HOST >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      env:
        SSH_USER: ${{ inputs.user }}
        SSH_KEY: ${{ inputs.key }}
        SSH_HOST: ${{ inputs.host }}

    - name: Execute deploy script
      shell: bash
      run: ssh ${{ inputs.user }}@${{ inputs.host }} './deploy-service.sh ${{ inputs.service }} ${{ inputs.sha }}'