name: 'Notify Macro Deck Extension'
description: 'Notify a Macro Deck Extension update in Discord'

inputs:
  upload-response:
    description: 'Response of the upload'
    required: true
  bot-token:
    description: 'Token for the Discord Bot'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Notify new plugin
      if: fromJSON(inputs.upload-response).newPlugin == true
      env:
        BOT_TOKEN: ${{ inputs.bot-token }}
      shell: bash
      run: |
        payload='{
          "toEveryone" : false,
          "embed" : {
            "color" : {
              "r":0,
              "g":1,
              "b":0
            },
            "title": "🎉 ${{ fromJSON(inputs.upload-response).name }} is now available in the Extension Store",
            "fields" : [
              {
                "name": "Description",
                "value": "${{ fromJSON(inputs.upload-response).description }}",
                "inline": false
              },
              {
                "name": "Author",
                "value": "${{ fromJSON(inputs.upload-response).author }}",
                "inline": false
              },
              {
                "name": "Repository URL",
                "value": "${{ fromJSON(inputs.upload-response).repository }}",
                "inline": false
              }
            ]
          }
        }'
        curl --fail-with-body -o "./bot-notify-response.json" -X POST \
          'https://bot.api.macro-deck.app/webhook/extension-store' \
          -H 'accept: */*' \
          -H "Authorization: Bearer ${{ env.BOT_TOKEN }}" \
          -H 'Content-Type: application/json' \
          -d "$payload" || cat "./bot-notify-response.json"


    - name: Notify update plugin
      if: fromJSON(inputs.upload-response).newPlugin == false
      env:
        BOT_TOKEN: ${{ inputs.bot-token }}
      shell: bash
      run: |
        payload='{
          "toEveryone" : false,
          "embed" : {
            "color" : {
              "r":0,
              "g":1,
              "b":1
            },
            "title": "🚀 ${{ fromJSON(inputs.upload-response).name }} was updated",
            "fields" : [
              {
                "name": "Version",
                "value": "${{ fromJSON(inputs.upload-response).currentVersion }} -> ${{ fromJSON(inputs.upload-response).newVersion }}",
                "inline": false
              },
              {
                "name": "Repository URL",
                "value": "${{ fromJSON(inputs.upload-response).currentVersion.repository }}",
                "inline": false
              }
            ]
          }
        }'
        curl --fail-with-body -o "./bot-notify-response.json" -X POST \
          'https://bot.api.macro-deck.app/webhook/extension-store' \
          -H 'accept: */*' \
          -H "Authorization: Bearer ${{ env.BOT_TOKEN }}" \
          -H 'Content-Type: application/json' \
          -d "$payload" || cat "./bot-notify-response.json"