name: Setup Capacitor and Ionic
description: "Action for setting up Capacitor and Ionic"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: >
        npm install -g yarn
        npm install -g @angular/cli
        npm install -g @ionic/cli
        npm install -g @capacitor/core
        npm install -g @capacitor/cli
        yarn install