name: Setup Capacitor and Ionic
description: "Action for setting up Capacitor and Ionic"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        npm install -g yarn
        yarn global add @angular/cli
        yarn global add @ionic/cli
        yarn global add @capacitor/core
        yarn global add @capacitor/cli
        yarn install